import React from 'react';

export const Act2SellOut: React.FC = () => {
  return (
    <div className="act2-stage absolute inset-0 z-20 flex flex-col items-center justify-center text-center px-6 pointer-events-none select-none">
      {/* Inherited 4-Column Ghost Grid (Visual continuity: Same film, new chapter) */}
      <div className="act2-ghost-grid absolute inset-0 grid grid-cols-[24.5%_24.5%_24.5%_26.5%] pointer-events-none opacity-0">
        <div className="border-r border-white/[0.08] h-full" />
        <div className="border-r border-white/[0.08] h-full" />
        <div className="border-r border-white/[0.08] h-full" />
        <div className="h-full" />
      </div>

      {/* Ambient Gold Halo Bridge Light (Generated by the surviving eclipse & gold particle) */}
      <div className="act2-ambient-gold absolute inset-0 bg-[radial-gradient(ellipse_at_center,rgba(236,208,142,0.18)_0%,rgba(184,135,63,0.06)_42%,transparent_72%)] pointer-events-none" />

      <div className="relative max-w-6xl flex flex-col items-center justify-center z-10">
        {/* Ambient Gold Flare */}
        <div className="sellout-gold-flare absolute -top-10 left-1/2 -translate-x-1/2 w-3/4 h-20 bg-gradient-to-r from-transparent via-[#ecd08e]/30 to-transparent blur-2xl pointer-events-none" />

        <div className="flex flex-col items-center justify-center leading-[1.04]">
          {/* Line 1: WE sell—out */}
          <div className="act2-line-1 flex items-baseline justify-center flex-wrap gap-2 sm:gap-4">
            <span className="act2-word-we font-sans font-extralight text-white/90 text-[clamp(2.4rem,5.2vw,5.4rem)] tracking-tight">
              WE
            </span>
            <span className="act2-sellout-wrap font-serif italic text-[#ecd08e] text-[clamp(3.6rem,8.0vw,8.4rem)] tracking-normal flex items-center">
              <span className="act2-word-sell">sell</span>
              <span className="act2-morph-hyphen inline-block w-6 sm:w-10 h-[2.5px] bg-[#ecd08e] mx-2 align-middle rounded-full shadow-[0_0_12px_#ecd08e]" />
              <span className="act2-word-out">out</span>
            </span>
          </div>

          {/* Line 2: your REAL ESTATE */}
          <div className="act2-line-2 flex items-baseline justify-center flex-wrap gap-3 sm:gap-5 mt-2 sm:mt-4">
            <span className="act2-your-dest font-serif italic font-normal text-[#ecd08e] text-[clamp(3.6rem,7.4vw,7.8rem)] select-none">
              your
            </span>
            <span className="act2-word-realestate font-sans font-black text-white text-[clamp(3.4rem,7.4vw,7.8rem)] tracking-[-0.04em] drop-shadow-[0_12px_50px_rgba(0,0,0,0.95)]">
              REAL ESTATE
            </span>
          </div>

          {/* Line 3: PROJECT. */}
          <div className="act2-line-3 font-sans font-extrabold text-[#d6d3cd] text-[clamp(2.6rem,5.8vw,6.0rem)] tracking-[-0.035em] mt-1 sm:mt-2 drop-shadow-[0_10px_40px_rgba(0,0,0,0.9)]">
            PROJECT.
          </div>
        </div>
      </div>
    </div>
  );
};
